seed: 1337
type: 'cls'
name: 'google/electra-base-discriminator'
tokenizer_max_length: 256
num_labels:
classifier_dropout: 0.
exists_in_repo: True  # whether the model exists in HF models repo
path_to_pretrained:  # required if the model does not exist in HF models repo
training:
    dev_size: 0.
    shuffle_dev: False
    freeze_embedder: False
    batch_size_args:
        batch_size: 16
        eval_batch_size: 100
        min_num_gradient_steps: 350
        adjust_batch_size: True
        adjust_num_epochs: True
        min_batch_size: 4
    trainer_args:
        num_epochs: 10
        patience: ${get_patience_value:${discriminator_model.training.dev_size}}
        grad_clipping: 1.
        serialization_dir: ./output/${to_string:${discriminator_model.name}}_${discriminator_model.seed}_${now:%Y-%m-%d}_${now:%H-%M-%S}/discriminator
        validation_metric: ${framework.validation_metric_cls}
        evaluation_strategy: 'no' # for transformers wrapper, 'epoch' or 'steps' or 'no'
        eval_metrics:
        fp16:
            training: True
            evaluation: False
        accumulation:
            gradient_accumulation_steps: 1
            eval_accumulation_steps:
    optimizer_args:
        weight_decay: 0.01
        lr: 2e-5
    scheduler_args:
        warmup_steps_factor: 0.1
        use_adafactor: False