cuda_devices: [0,1,2]
task_names: ''
hydra:
  run:
    dir: ./workdir/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    
tasks:
    - 
        name: 'bart-base'
        config_path: '../configs'
        config_name: 'al_abssum_pl'
        command: '../../../active_learning/active_learning/run_active_learning.py'
        environ: ''
        args: 'data.dataset_name=aeslc data.text_name=email_body data.label_name=subject_line acquisition_model.name=facebook/bart-base al.strategy=random al.init_p_or_n=10 al.step_p_or_n=10 +al.plasm_thresh=[0.1,0.01]'
        seeds: [10671619, 1084218, 42, 123, 12345, 9876543, 4837, 23419, 705525]
        n_repeats: 1